spring:
  application:
    name: booking
  datasource:
    url: jdbc:h2:mem:bookingdb
    username: sa
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

server:
  port: 8080
